spring:
  application:
    name: MulMooRi_Monolithic_API
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

---

spring:
  config:
    activate:
      on-profile: dev

---